export type Palette = {
  canvas: string;
  surface: string;
  sunken: string;
  ink: string;
  muted: string;
  faint: string;
  line: string;
  lineStrong: string;
  positive: string;
  positiveSoft: string;
  negative: string;
  negativeSoft: string;
  accent: string;
  accentSoft: string;
  overlay: string;
  brandCyan: string;
  brandBlue: string;
  brandYellow: string;
  brandRed: string;
  brandGreen: string;
  brandInk: string;
  brandPaper: string;
  brandCyanSoft: string;
  brandBlueSoft: string;
  brandYellowSoft: string;
  brandRedSoft: string;
  brandGreenSoft: string;
};

declare const palettes: { light: Palette; dark: Palette };
export = palettes;
